// Runtime bindings come from Wrangler's generated CloudflareBindings. Secrets
// and feature flags are optional in testnet/local environments and validated
// explicitly by runtimeConfig before mainnet traffic is accepted.
type OptionalBindingKey =
	| "ALLOWED_ORIGINS"
	| "OPS_HEALTH_TOKEN"
	| "FAUCET_PRIVATE_KEY"
	| "RECOVERY_GUARDIAN_PRIVATE_KEY"
	| "PAYMASTER_SIGNER_PRIVATE_KEY"
	| "SPONSORSHIP_PROVIDER"
	| "SPONSORSHIP_FALLBACK_PROVIDER"
	| "SPONSORSHIP_PAYMASTER_ADDRESS"
	| "SPONSORSHIP_HEALTH_CHECK_ENABLED"
	| "PAYMASTER_SERVICE_URL"
	| "PAYMASTER_SERVICE_CONTEXT_JSON"
	| "PAYMASTER_SERVICE_EXPECTED_PAYMASTER"
	| "PAYMASTER_SERVICE_TIMEOUT_MS"
	| "PAYMASTER_MIN_DEPOSIT_WEI"
	| "PAYMENT_ROUTER_SIGNER_PRIVATE_KEY"
	| "TURNSTILE_SECRET_KEY"
	| "FCM_SERVICE_ACCOUNT"
	| "FIREBASE_SERVICE_ACCOUNT"
	| "FIREBASE_WEB_API_KEY"
	| "AUTH_CODE_PEPPER"
	| "AUTH_EMAIL_FROM"
	| "APP_URL"
	| "GATOPAGO_FEES_ENABLED"
	| "GATOPAGO_SWAP_FEE_BPS"
	| "GATOPAGO_MAX_FEE_BPS"
	| "GATOPAGO_TREASURY_ADDRESS"
	| "GATOPAGO_CROSSCHAIN_FEE_BPS"
	| "CCTP_RPC_URLS"
	| "CROSSCHAIN_PAUSED"
	| "CROSSCHAIN_DISABLED_CHAINS"
	| "CROSSCHAIN_MIN_RELAYER_GAS_WEI"
	| "EARN_PAUSED"
	| "FAUCET_ENABLED"
	| "FAUCET_DAILY_BUDGET_USDC"
	| "RPC_READ_URLS"
	| "RPC_WRITE_URLS"
	| "RPC_INDEXER_URLS"
	| "RPC_ARCHIVE_URLS"
	| "RPC_PROVIDER_CAPABILITIES"
	| "BUNDLER_RPC_URLS"
	| "RPC_TIMEOUT_MS"
	| "RPC_INDEXER_MAX_BLOCK_RANGE"
	| "RPC_INDEXER_MIN_BLOCK_RANGE"
	| "INDEXER_WALLET_SHARD_SIZE"
	| "INDEXER_REGISTRY_BATCH_SIZE"
	| "INDEXER_MAX_RPC_CALLS_PER_JOB"
	| "INDEXER_MAX_BLOCKS_PER_JOB"
	| "INDEXER_MAX_EVENT_BLOCKS_PER_JOB"
	| "INDEXER_SAFETY_SWEEP_SECONDS"
	| "BALANCE_MAX_STALENESS_SECONDS"
	| "ARBITRUM_L1_CONFIRMATIONS_REQUIRED"
	| "RELAYER_MODE"
	| "BUNDLER_ROLLOUT_PERCENT"
	| "BUNDLER_SELF_FALLBACK"
	| "BUNDLER_DUMMY_SIGNATURE"
	| "ALCHEMY_WEBHOOK_ENABLED"
	| "ALCHEMY_WEBHOOK_ID"
	| "ALCHEMY_WEBHOOK_NETWORK"
	| "ALCHEMY_WEBHOOK_SIGNING_KEY"
	| "ALCHEMY_ADDRESS_WEBHOOKS_JSON"
	| "ALCHEMY_NOTIFY_AUTH_TOKEN"
	| "ALCHEMY_CUSTOM_WEBHOOK_ENABLED"
	| "ALCHEMY_CUSTOM_WEBHOOK_ID"
	| "ALCHEMY_CUSTOM_WEBHOOK_SIGNING_KEY"
	| "WEBHOOK_SECRET_ENCRYPTION_KEY"
	| "WEBHOOK_SECRET_ENCRYPTION_KEY_ID"
	| "WEBHOOK_SECRET_ENCRYPTION_KEYS_PREVIOUS"
	| "PAYMENTS_CUTOVER_MODE"
	| "PAYMENTS_SYNC_ENABLED";

type StringBindingKey = {
	[Key in keyof CloudflareBindings]-?: CloudflareBindings[Key] extends string ? Key : never;
}[keyof CloudflareBindings];

// Wrangler preserves literal values from `vars` in generated types. Runtime
// deployments legitimately override those values per environment, so expose
// every string binding as `string` while retaining D1 and other binding types.
type OptionalInfrastructureBindings =
	| "SCHEDULED_JOBS_QUEUE"
	| "EVENT_JOB_SCHEDULER"
	| "RPC_ADMISSION"
	| "PAYMENTS"
	| "EMAIL";

export type Bindings = Omit<CloudflareBindings, StringBindingKey | OptionalInfrastructureBindings> &
	Record<Exclude<StringBindingKey, OptionalBindingKey>, string> &
	Partial<Record<OptionalBindingKey, string>> &
	Partial<Pick<CloudflareBindings, OptionalInfrastructureBindings>>;
